name: 'The Repo Ranker'
description: 'Rank some repositories'
branding:
  icon: 'arrow-up-right'
  color: 'orange'
inputs:
  openai-api-key:
    description: 'OpenAI API Key'
    required: true
    default: ''
  github-token:
    description: 'Github API Key'
    required: true
    default: ''
  openai-engine:
    description: 'GPT-3.5 models can understand and generate natural language. We offer four main models with different levels of power suitable for different tasks. Davinci is the most capable model, and Ada is the fastest.'
    required: false
    default: 'gpt-3.5-turbo'
  openai-temperature:
    description: 'What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.'
    required: false
    default: '0.0'
  openai-max-tokens:
    description: 'The maximum number of tokens to generate in the completion.'
    required: false
    default: '4096'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai-api-key }}
    - ${{ inputs.github-token }}
    - ${{ inputs.openai-engine }}
    - ${{ inputs.openai-temperature }}
    - ${{ inputs.openai-max-tokens }}
