name: Simple Repo Ranker

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC

  workflow_dispatch:

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: Simple Repo Ranker
    steps:
      - name: Simple Repo Ranker code
        uses: anabramo/simple-repo-ranker@main
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GH_TOKEN }}
          openai-engine: "gpt-3.5-turbo"
          openai-temperature: 0.0
          openai-max-tokens: 4096
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build Docs
        run: npm i && npm run build:docs
      - name: Commit and push changes
        run: |
          git config --global user.name 'anabramo'
          git config --global user.email 'andrey.abramov@bjss.com'
          git add .
          git commit -am "Updates" || exit 0
          git push https://${{ secrets.GH_TOKEN }}@github.com/